parameters:
  - name: stageName
    type: string
    default: Linux_Build

  - name: pool
    type: string
    default: DevCentral-VeriStand-CustomDevices

  # lvVersionsToBuild (optional): list of {version, bitness}
  - name: lvVersionsToBuild
    type: object
    default:
      - version: '2026'
        bitness: '64bit'

  # buildSteps (optional): list of {projectLocation, buildOperation, target, buildSpec}
  - name: buildSteps
    type: object
    default: ''

  # strings (releaseVersion, quarterlyReleaseVersion, buildOutputLocation, archiveLocation)
  - name: releaseVersion
    type: string
  - name: buildOutputLocation
    type: string
  - name: archiveLocation
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: []
    variables:
        CD.BuildCounter: "9999"
    pool:
      name: ${{ parameters.pool }}
    jobs:
        # Build Jobs
      - ${{ each item in parameters.lvVersionsToBuild }}:
        - job: Job_Build_${{ item.version }}_${{ item.bitness }}
          pool:
            name: ${{ parameters.pool }}
            demands: 
              - agent.os -equals Linux
          displayName: Linux - Build LabVIEW ${{ item.version }} ${{ item.bitness }}
          timeoutInMinutes: 120
          steps:
            - task: PowerShell@2
              displayName: Linux Build - Debug Info
              inputs:
                targetType: inline
                script: |
                  Write-Host "Build.SourcesDirectory = $(Build.SourcesDirectory)"
                  Write-Host "System.DefaultWorkingDirectory = $(System.DefaultWorkingDirectory)"

                  Write-Host "Current directory:"
                  pwd

                  Write-Host "Listing contents:"
                  ls -la
