parameters:
  - name: stageName
    type: string
    default: Linux_Build

  - name: pool
    type: string
    default: DevCentral-VeriStand-CustomDevices

  - name: lvVersionsToBuild
    type: object
    default:
      - version: '2026'
        bitness: '64bit'

  - name: buildSteps
    type: object
    default: []

  - name: releaseVersion
    type: string

  - name: buildOutputLocation
    type: string

  - name: archiveLocation
    type: string
  
  - name: branch
    type: string
    default: main

  - name: debugBuild
    type: string
    default: no

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: []

    variables:
      CD.BuildCounter: "9999"

    pool:
      name: ${{ parameters.pool }}

    jobs:

      - ${{ each item in parameters.lvVersionsToBuild }}:
        - ${{ each buildStep in parameters.buildSteps }}:

          - job: Job_Build_${{ item.version }}_${{ item.bitness }}_${{ buildStep.id }}

            pool:
              name: ${{ parameters.pool }}
              demands:
                - agent.os -equals Linux

            displayName: >
              Linux - Build ${{ buildStep.projectLocation }}
              (LV ${{ item.version }} ${{ item.bitness }})

            timeoutInMinutes: 120

            steps:
              - task: Bash@3
                displayName: Build ${{ buildStep.projectLocation }}
                inputs:
                  targetType: inline
                  script: |
                    projectPath="$(Build.SourcesDirectory)/${{ buildStep.projectLocation }}"

                    echo "Project Path: $projectPath"

                    # Give LabVIEW enough time to initialize VI Server
                    sleep 30

                    xvfb-run --auto-servernum LabVIEWCLI \
                      -LabVIEWPath "/usr/local/natinst/LabVIEW-${{ item.version }}-64/labview" \
                      -PortNumber 3363 \
                      -OperationName "${{ buildStep.buildOperation }}" \
                      -ProjectPath "$projectPath" \
                      -TargetName "${{ buildStep.target }}" \
                      -BuildSpecName "${{ buildStep.buildSpec }}"